### ISSUE TITLE
Deprecation warning?

### ISSUE THREAD

**Issue by njt1982** [geerlingguy/ansible-role-git#20]
```
TASK [geerlingguy.git : Get installed version] *********************************
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..

This feature will be removed in version 2.4. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
```

Is this something to be concerned about?

**Comment by geerlingguy** [comment]
@njt1982 - No, I'm waiting to change that until 2.3 is out, because that new variable was just introduced in 2.2. It's mildly annoying that the variable will be deprecated so quickly, because I still have a lot of users on 2.0 and 2.1!

So once 2.3 is released, I'm going to update this variable in all my roles and bump the minimum required version to 2.2.

**Comment by njt1982** [comment]
Thanks @geerlingguy 👍
