### ISSUE TITLE
Has a dependency on running apt-get update

### ISSUE THREAD

**Issue by pmackay** [geerlingguy/ansible-role-git#6]
Running this as the first role in a playbook, it fails initially but works if `apt-get update` is run. Should this be included as a step? If not, it would be helpful if the README suggested this as a dependency.

**Comment by geerlingguy** [comment]
Added in as a normal role task; for most of my debian playbooks, I always have an apt update task as a pre_task anyways, which is why I never notice if it's missing in any of my roles. But I've been adding it as the first task for Debian-based installs lately just because it's simpler for those who don't always add it as a pre task :)
